#!/usr/bin/env python3
"""Export the MQGT-SCF extended periodic workbook as static site data."""

from __future__ import annotations

import json
from pathlib import Path

from openpyxl import load_workbook


ROOT = Path(__file__).resolve().parents[1]
WORKBOOK_PATH = ROOT / "docs/assets/MQGT_SCF_Extended_Periodic_Table_1-184.xlsx"
OUTPUT_PATH = ROOT / "docs/extended-periodic-table/periodic-data.js"


HEADER_MAP = {
    "Z": "z",
    "Symbol": "symbol",
    "Name": "name",
    "Status": "status",
    "Period": "period",
    "Group/Slot": "groupSlot",
    "Block": "block",
    "Family/Class": "familyClass",
    "MQGT–SCF ToE Band": "band",
    "Matter Mode": "matterMode",
    "Flow-Metal Role": "flowMetalRole",
    "Ψ Orbital/Shell Note": "psiNote",
    "Φc Index (toy)": "phiCIndex",
    "E(x) Stability Bias": "stabilityBias",
    "Confidence Tier": "confidenceTier",
    "Source Note": "sourceNote",
}


def scalar(value):
    if isinstance(value, float):
        return round(value, 4)
    return value


def parse_slot(slot):
    text = str(slot or "")
    if text.isdigit():
        return int(text)
    for prefix in ("Ln", "Act", "G", "F", "Ω"):
        if text.startswith(prefix):
            try:
                return int(text[len(prefix) :])
            except ValueError:
                return None
    return None


def layout_for(row):
    z = row["z"]
    slot = str(row["groupSlot"])
    period = row["period"]
    block = row["block"]
    band = row["band"]
    slot_number = parse_slot(slot)

    if z <= 118:
        if slot.startswith("Ln"):
            return {"zone": "core", "row": 8, "col": 3 + (slot_number or 1) - 1, "lane": "Lanthanides"}
        if slot.startswith("Act"):
            return {"zone": "core", "row": 9, "col": 3 + (slot_number or 1) - 1, "lane": "Actinides"}
        return {"zone": "core", "row": period, "col": slot_number, "lane": f"Period {period}"}

    if z >= 169:
        if z <= 170:
            return {"zone": "extended", "row": 6, "col": slot_number, "lane": "9s restart + boundary"}
        return {"zone": "extended", "row": 6, "col": 2 + (slot_number or 1), "lane": "9s restart + boundary"}
    if block == "g":
        return {"zone": "extended", "row": 2, "col": slot_number, "lane": "5g hyperorbital braid"}
    if block == "f":
        return {"zone": "extended", "row": 3, "col": 2 + (slot_number or 1), "lane": "6f superactinide memory"}
    if block == "d":
        return {"zone": "extended", "row": 4, "col": slot_number, "lane": "7d flow-metal return"}
    if block == "p":
        return {"zone": "extended", "row": 5, "col": slot_number, "lane": "8p closure"}
    if band == "Charge reservoir / ignition shell":
        return {"zone": "extended", "row": 1, "col": slot_number, "lane": "8s ignition"}

    return {"zone": "extended", "row": 6, "col": slot_number, "lane": "Supercritical boundary"}


def read_elements(wb):
    ws = wb["1-184 Table"]
    headers = [ws.cell(1, col).value for col in range(1, ws.max_column + 1)]
    elements = []

    for row_index in range(2, ws.max_row + 1):
        raw = {
            HEADER_MAP[headers[col_index - 1]]: scalar(ws.cell(row_index, col_index).value)
            for col_index in range(1, ws.max_column + 1)
        }
        raw["confirmed"] = raw["z"] <= 118
        raw["layout"] = layout_for(raw)
        raw["searchText"] = " ".join(str(raw[key]) for key in raw if key not in {"layout", "searchText"}).lower()
        elements.append(raw)

    if len(elements) != 184:
        raise ValueError(f"Expected 184 elements, found {len(elements)}")
    return elements


def read_summary(wb):
    ws = wb["Summary"]
    metrics = {}
    for row in range(2, 7):
        key = ws.cell(row, 1).value
        value = ws.cell(row, 2).value
        if key:
            metrics[str(key)] = scalar(value)

    bands = []
    for row in range(9, ws.max_row + 1):
        band = ws.cell(row, 1).value
        if not band:
            continue
        bands.append(
            {
                "band": band,
                "range": ws.cell(row, 2).value,
                "count": ws.cell(row, 3).value,
                "interpretation": ws.cell(row, 4).value,
            }
        )
    return {"metrics": metrics, "bands": bands}


def main():
    wb = load_workbook(WORKBOOK_PATH, data_only=True)
    payload = {
        "meta": {
            "title": "MQGT-SCF Extended Periodic Table",
            "range": "Z=1-184",
            "sourceWorkbook": "../assets/MQGT_SCF_Extended_Periodic_Table_1-184.xlsx",
            "caution": "Elements Z=119-184 are theoretical placeholders and are not experimentally confirmed.",
        },
        "summary": read_summary(wb),
        "elements": read_elements(wb),
    }

    OUTPUT_PATH.write_text(
        "/* Generated by scripts/export_mqgt_periodic_data.py from the source workbook. */\n"
        f"window.MQGT_PERIODIC_DATA = {json.dumps(payload, ensure_ascii=False, indent=2)};\n",
        encoding="utf-8",
    )
    print(f"Wrote {OUTPUT_PATH.relative_to(ROOT)} ({len(payload['elements'])} elements)")


if __name__ == "__main__":
    main()
